### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by X-712** [cniu6/douyinpaging#1]
直接双击窗口弹出后消失，用cmd打开显示如下
![image](https://github.com/cniu6/douyinpaging/assets/165975757/256704b7-6e0f-4e40-9d78-d0fb17078ae5)
请问该怎么办

**Comment by cniu6** [comment]
本人感觉是win7问题，我这边用的是win10编译打包，并且使用正常，可能python不向下兼容。
解决办法，
克隆项目源码
win7安装Python3.9并且运行，使用pyinstaller打包成可执行文件,方便使用。



---------下面是ai给出的解答---------


这个错误信息表明，Python 在尝试初始化文件系统编码时遇到了问题，并且这个问题在尝试导入某些模块时引发了。具体错误信息包含了几个关键点：

1.  `init_fs_encoding: failed to get the Python codec of the file system encoding` - 这意味着 Python 无法获取文件系统编码的 Python 编码器。
    
2.  `KeyError: 'C:\\\\Users\\\\X\\\\AppData\\\\Local\\\\Temp\\\\_MEI32082\\\\base_1ibrary.zip'` - 这个错误表明 Python 在尝试访问一个特定的 zip 文件时找不到键，这通常意味着文件路径错误或者文件损坏。
    
3.  `SystemError: Negative size passed to PyUnicode_New` - 这个错误发生在尝试创建一个新的 Unicode 字符串时，传递了一个负数大小。
    

以下是一些可能的解决方案：

### 解决方案 1：检查文件路径和文件完整性

确保 `C:\\\\Users\\\\X\\\\AppData\\\\Local\\\\Temp\\\\_MEI32082\\\\base_1ibrary.zip` 路径正确，且该文件没有损坏。

### 解决方案 2：清理临时文件夹

有时，临时文件可能会导致这类问题。可以尝试删除 `C:\\\\Users\\\\X\\\\AppData\\\\Local\\\\Temp\\\\_MEI32082` 文件夹中的内容。

### 解决方案 3：重新安装 Python

如果以上步骤都不奏效，可能需要重新安装 Python。安装时确保选择正确的编码设置。

### 解决方案 4：检查环境变量

检查系统环境变量，特别是 `PYTHONHOME` 和 `PYTHONPATH`，确保它们设置正确。

下面是一个简单的 Python 脚本，用于检查和清理临时文件夹：

    import os
    import shutil
    
    # 定义临时文件夹路径
    temp_dir = r'C:\\Users\\X\\AppData\\Local\\Temp\\_MEI32082'
    
    # 检查路径是否存在
    if os.path.exists(temp_dir):
        # 尝试删除文件夹
        try:
            shutil.rmtree(temp_dir)
            print(f"临时文件夹 '{temp_dir}' 已被删除。")
        except Exception as e:
            print(f"删除临时文件夹时出错：{e}")
    else:
        print(f"路径 '{temp_dir}' 不存在。")
    

运行这个脚本前，请确保将路径修改为实际存在的路径。如果问题依然存在，可能需要考虑其他解决方案。
